# App config
server:
  port: 8102

spring:
  application:
    name: Movie Service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # cambiar a http://eureka-server:8761/eureka cuando se levante Api Gateway

#Actuator: Monitoreando la salud de nuestros microservicios
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
info:
  app:
    name: Movie Service
    description: El microservicio gestiona las operaciones sobre las películas
    version: 1.0.0
